### ISSUE TITLE
Okta Permissions Issues - IDM

### ISSUE THREAD

**Issue by stephanieboydcms** [Enterprise-CMCS/eAPD#4397]
Per thread below, I have placed ticket REQ0200069 via CMSConnect to resolve and will update accordingly.  Also attaching original email from Tim.

From: Keith Majette <[keith.majette@banasolutions.com](mailto:keith.majette@banasolutions.com)> 
Sent: Friday, November 4, 2022 7:00 AM
To: Lee, Jerome (CMS/CMCS) <[Jerome.Lee@cms.hhs.gov](mailto:Jerome.Lee@cms.hhs.gov)>
Subject: Re: [EXTERNAL] RE: INC1280384 - PROD/IMPL/MACPro-EAPD - Registration Link Issue

Good morning Jerome, sorry for the delay.  This link was provided to me regarding the SR question you had.  
[IDM Service Request Creation Process](https://confluenceent.cms.gov/display/IDM/IDM+Service+Request+Creation+Process)
[9:31](https://cmsgov.slack.com/archives/D03SD2D1HD5/p1667568702721979)
here is the tiny link: https://confluenceent.cms.gov/x/0AHFAQ
Hopefully this will help.  If so let me know and I'll cancel the ticket.

Hello,

We just received notification that our Okta admins are having their write permissions removed, which seems like it would directly affect our ability to utilize this form to grant people access through Okta in the IMPL environment. 

Stephanie Boyd, part of the product team, is doing some research into the potential effects on this notification, but for now it seems that we can cancel this ticket and we’ll put in a ticket through the link provided by Keith Majette.

Thank you,
Jerome

**Comment by jeromeleecms** [comment]
This is still in progress. OIT needs to figure out how to implement this.

**Comment by stephanieboydcms** [comment]
IDM-44620 has been created:  

Follow up to the IDM SR Ticket was created by REQ0180957/RITM0182150 / [IDM-42852](https://jiraent.cms.gov/browse/IDM-42852) 
Please make the following changes in the IMPL environment:
    In the test environment, when users sign up using this link https://test.reg.idm.cms.gov/registration.html?appid=eapd they are automatically added to our application and user group. We would like a link like that in the impl environment so that users are automatically assigned to our application and group.

   We need to confirm TEST environment and then setup the IMPL and then eventually PROD

 

What we need to decide if this is bigger then a Incident or SR where this may need to be an Onboarding Process item.

**Comment by stephanieboydcms** [comment]
Update:  IDM-42852 was closed and IDM-44620 was created.  
William Liggett added a comment - 20/Dec/22 8:36 PM
Tonight, we deployed code changes to support this ticket on the TEST environment, but there will be further development activities throughout the week before closing out this effort.

**Comment by jeromeleecms** [comment]
We are working on seeing if the proposed link will work - more updates on this once it has been tested.

**Comment by jeromeleecms** [comment]
This is done; I still have access to perform this operations.
